### ISSUE TITLE
Unclear error message when passing cell-array to controller object without outputs

### ISSUE THREAD

**Issue by AndreasHempel** [embotech/Y2F#12]
When passing a cell array of parameter values to a `controller` object without requesting output arguments, e.g. (based on the `mpc_parametric_inequalities.m` example)
```
controller{ {X(:,k), r1, r2} }
```
the call fails with the cryptic error message
```
Error using numel
Bad subscripting index.
```

On the other hand, handing the parameter values to the `controller` **not** as a cell array, i.e.
```
controller{ X(:,k), r1, r2 }
```
works and prints the values of the first two output arguments (requested solver output and `exitflag`) to the console like so:
```
>> controller{ X(:,k), r1, r2 }

ans =

  -6.5191e-07


ans =

     1
```

A solution would be to detect the error when calling the controller object and printing an appropriate error message. Probably #11 should be resolved first since it seems related.

**Comment by GianUlli** [comment]
This was a bug. It was fixed with commit 85040617dcc4e9fe4796bc6c3bfec8c1a6313b98. Had something to do with the way Matlab determines the output size when indexing a class.
