### ISSUE TITLE
Printlevel settings are ignored

### ISSUE THREAD

**Issue by AndreasHempel** [embotech/Y2F#13]
By default, `getOptions` sets the printlevel to 2. The same should be expected of Y2F but it seems the user-specified setting for printlevel is ignored: when calling the mex-interface for a solver generated with Y2F, no output from the solver-call is printed to the screen.

I remember this being different in an earlier version. The change may be a result of the 'new' mex-interface generation (commit 12ab87957a9acf1c997a0a64425830eee5ac1297 ?) or what file-pointer is handed to the generated solver.

**Comment by GianUlli** [comment]
You are right, it had been introduced with that commit. It was fixed with commit e553ff230b5dc8f434f695d35955e84cabf25dcd.
