### ISSUE TITLE
Respect option 'BuildSimulinkBlock'

### ISSUE THREAD

**Issue by adomahidi** [embotech/Y2F#16]
In FORCES, one can skip compilation of the Simulink block by specifying `codeoptions. BuildSimulinkBlock=0`. It would be great to have the same feature in y2f to accelerate design iterations when only the Matlab MEX function is of interest.

**Comment by GianUlli** [comment]
This functionality was added with commit 43d08cab3388472cd4a65df69a5f5fd38f1ac741.
