### ISSUE TITLE
Use the names of sdpvar-objects to name the solver-parameters and -outputs

### ISSUE THREAD

**Issue by AndreasHempel** [embotech/Y2F#2]
Currently, the parameters and outputs of the solver generated by Y2F are named simply with consecutive numbers (p_1, p_2, ... and o_1, o_2, ...). It would be great to specify their names by using the variable names of the original YALMIP sdpvar objects.

For example, if I have a constraint like `con = xvar(:,1) == xinit` to set the initial state of a dynamical system and later call Y2F with `options = getOptions('solvername')` and `solver = optimizerFORCES(con, obj, options, xinit, xvar)` I want there to be a solver-parameter called 'xinit' such that I can then call the solver with `solvername(struct('xinit', x0))`.

MATLAB does not have proper support for this sort of [reflection](https://en.wikipedia.org/wiki/Reflection_%28computer_programming%29), but there exists a [workaround](http://stackoverflow.com/a/11453337) that could be used.

**Comment by AndreasHempel** [comment]
This functionality is necessary in particular to use the generated Simulink interface to the solver.

**Comment by GianUlli** [comment]
The FORCES parameters generated by Y2F are generally not in a one-to-one relation to the YALMIP parameters defined by the users. Parts of the YALMIP parameter might end up in different stages, so multiple FORCES parameters are generated. Implementing a meaningful naming scheme would be very hard.

To solve the issue with the Simulink interface, a solution would be to generate a Simulink block with Y2F.

**Comment by GianUlli** [comment]
With the separate C interface and the Simulink block that are now generated by Y2F, this should no longer be a problem. The user has the option to add names for parameters/output that are used in the C interface and the Simulink block.
