### ISSUE TITLE
Print detected stage sizes

### ISSUE THREAD

**Issue by adomahidi** [embotech/Y2F#20]
As a y2f user,

I would like to make sure y2f detected the right structure.

Notes:
It would be very useful to print the detected stage dimensions before generating code with FORCES so one can quickly check whether something went wrong in the detection. I recently worked with this code to the file `optimizerFORCES.m` (line 353), which could be extended or made nicer but it does the job:

```
% print size of variables 
    fprintf('Number of variables          : ');
    for n = 1:length(stages{i})
        fprintf('%2d  ', stages{i}(n).dims.n);
    end
    fprintf('\n');
    
    % print size of equality constraints
    fprintf('Size of equality constraints : ');
    for n = 1:length(stages{i})
        fprintf('%2d  ', stages{i}(n).dims.r);
    end
    fprintf('\n');
    
    % size of polytopic constraints
    fprintf('Size of polytopic constraints: ');
    for n = 1:length(stages{i})
        fprintf('%2d  ', stages{i}(n).dims.p);
    end
    fprintf('\n');
```

**Comment by g-ulli** [comment]
Solved in `v0.1.15`
