### ISSUE TITLE
there are some problems when I run the exmple of y2f

### ISSUE THREAD

**Issue by lbhammer** [embotech/Y2F#22]
environment：matlab 2018b, yalmip20190425, y2f0.1.15
when I run the exmple of y2f(mpc_basic_exmple), there are some problems in my matlab:
1.Undefined function or variable 'getOptions'。
error mpc_basic_example (line 78)
codeoptions = getOptions('simpleMPC_solver'); % give solver a name
2. when I solver the proble with"codeoptions.name = 'simpleMPC_solver'",there are still some problems:
YALMIP-to-FORCES code generator
-------------------------------
This is Y2F (v0.1.15), the YALMIP interface of FORCES Pro.
For more information visit https://github.com/embotech/y2f

Using YALMIP to convert problem into QP...   [OK,   0.1 sec]
Extract parameters and quadratic inequalities from YALMIP model...   [OK,   0.0 sec]
Assembling stages...Undefined function or variable 'MultistageProblem'。

error generateStagesFromGraph (line 38)
stages = MultistageProblem(G.n);

error stagesFromPathGraphs (line 46)
        [stages_temp,params_temp,standardParamValues_temp,forcesParamMap_temp] =
        generateStagesFromGraph(components{i},H,f,Aineq,bineq,Aeq,beq,l,Q,r,lb,ub,qcqpParams,yalmipParamMap);

error  optimizerFORCES (line 300)
    stagesFromPathGraphs(graphComponents,H,f,Aineq,bineq,Aeq,beq,l,Q,r,lb,ub,qcqpParams,yalmipParamMap,outputIdx);

error mpc_basic_example (line 80)
controller = optimizerFORCES(const, cost, codeoptions, X(:,1), U(:,1), {'xinit'}, {'u0'});

**Comment by g-ulli** [comment]
This sounds like you do not have [FORCES Pro](https://www.embotech.com/forces-pro/) on the Matlab path.

**Comment by lbhammer** [comment]
> This sounds like you do not have FORCES Pro on the Matlab path.

Thank you for your response. I will have a try.
