### ISSUE TITLE
Minimal example in help not working

### ISSUE THREAD

**Issue by adomahidi** [embotech/Y2F#3]
When I do `help optimizerFORCES`

the following minimal example is displayed:

```
sdpvar x y p
solver = optimizerFORCES([x + y == p], x^2+y^2, options, p, {x,y})
solution = solver{5} % solve problem for p = 5
```

... but this is not working

**Comment by GianUlli** [comment]
Thanks. Issue has been fixed with commit c6841a5db98cc0bb338e7ccaf74f46eb785a1673.
