### ISSUE TITLE
Parametric cost not working?

### ISSUE THREAD

**Issue by adomahidi** [embotech/Y2F#5]
I have added an example (examples/mpc_parametric_cost) where the Q,R,P matrices of the simple MPC example are parametric.
Doesn't quite work yet - what am I doing wrong?

**Comment by GianUlli** [comment]
So far, solvers generated using optimizerFORCES could be called using
`controller{ {param_value1, param_value2, …} }` (notice the cell array as argument). Now, with commit 95cdf34d107b2ffebdeb7d3f5d5be723cafdf1fd, `controller{ param_value1, param_value2, …
}` works, too. This should solve the issue.
